spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 280452
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
#常规配置
    initialSize: 5
    minIdle: 5


#    配置监控统计拦截的filters，去掉后监控界面的SQL无法统计，walls用于防火墙
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    #  配置redis
    #默认redis数据库为db0
  redis:
    database: 0
    host: 192.168.31.80
    port: 6379
  mail:
    host: smtp.qq.com
    username: 997150986@qq.com
    password: rwebjgxzaxxlbdcg
    default-encoding: UTF-8
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
    packages:
      trust-all: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql
server:
  port: 8888

logging:
  config: classpath:log4j2.xml
mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.springboot.springbootjdbc.dao